### ISSUE TITLE
Init на стороне сервера

### ISSUE THREAD

**Issue by itlogic** [TinkoffCreditSystems/AcquiringSdkAndroid#11]
Бизнес логика нашего проекта подразумевает Вызов Init и последующую проверку статуса по PaymentID на стороне бэка. Есть ли возможность сделать вызов openPaymentScreen с передачей уже существующего PaymentID ??

**Comment by MaryAPc** [comment]
Здравствуйте! Возможность есть, для этого передайте в последний параметр метода openPaymentScreen state=SelectCardAndPayState, который принимает PaymentID.
Пример:
`tinkoffAcquiring.openPaymentScreen(this, createPaymentOptions(), PAYMENT_REQUEST_CODE, SelectCardAndPayState(paymentId))`
