### ISSUE TITLE
Вызов openPaymentScreen из java

### ISSUE THREAD

**Issue by mkruglikov** [TinkoffCreditSystems/AcquiringSdkAndroid#12]
Не удаётся вызвать `tinkoffAcquiring.openPaymentScreen(activity, options, requestCode)` из Java, т.к. требуется четвёртый аргумент state.
`AsdkState.DefaultState` передать не выходит, он приватный.

Возможно, нужен [JvmOverloads](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-overloads/)

**Comment by MaryAPc** [comment]
Здравствуйте! Попробуйте передать state как DefaultState.INSTANCE.
В следующей версии установлю аннотацию JvmOverloads для этого метода
