### ISSUE TITLE
Оплата через фрагменты

### ISSUE THREAD

**Issue by TooLazyy** [TinkoffCreditSystems/AcquiringSdkAndroid#20]
Не вижу возможности запустить флоу оплаты через фрaгмент. Требуется зачем то в обязательно порядке инстанс активити.
Единственную возможность вижу в копировании нужного интента из openPaymentScreen и BaseAcquiringActivity.createIntent, что звучит довольно дико.

**Comment by MaryAPc** [comment]
Экран оплаты действительно нельзя запустить как фрагмент. Ссылка на активити нужна для того, чтобы вернуть результат операции и клиент имел возможность обработать его в onActivityResult. Если вы запускаете экран оплаты из фрагмента, вы можете передать в первый параметр getActivity() или requireActivity()

**Comment by TooLazyy** [comment]
Я прекрасно вижу для чего нужен экземпляр активити. Проблема только в том, что вызов activity.startAactivityForResult вернет результат в активити, а при работе с single activity (ну или с минимум активити) хочется получить результат по месту вызова в фрагменте. Вызов fragment.startActivityForResult таким же образом вернет результат сразу в нужный фрагмент.
Сейчас, Если я хочу получить результат в фрагмент, мне нужно либо из активити его ловить и пробрасывать, либо ручками создавать интент, скопировав BaseAcquiringActivity.createIntent

**Comment by MaryAPc** [comment]
Поняла вас, добавим возможность запуска из фрагмента в следующей версии, релиз предположительно будет на этой неделе

**Comment by TooLazyy** [comment]
@MaryAPc помочь пр-ом?)

**Comment by MaryAPc** [comment]
Спасибо, но уже нет, я в сейчас процессе проверки возврата результата во фрагменты)

**Comment by TooLazyy** [comment]
@MaryAPc google pay оплата тоже через фрагменты будет доступна?

**Comment by MaryAPc** [comment]
Которая из уведомления или по кнопке?

**Comment by TooLazyy** [comment]
по кнопке

**Comment by MaryAPc** [comment]
По кнопке к сожалению не получится сделать передачу фрагмента, вместо активити в методе `openGooglePay`. Там проблема в самой гугловой библиотеке, она не поддерживает возврат результата во фрагмент, только в активити

**Comment by MaryAPc** [comment]
Добавлено в версии 2.2.0
