### ISSUE TITLE
Добавить возможность самостоятельно обрабатывать все ошибки оплаты

### ISSUE THREAD

**Issue by memphisprog** [TinkoffCreditSystems/AcquiringSdkAndroid#22]
На данный момент SDK сам обрабатывает ошибки и отображает свой экран для кодов

```
val errorCodesForUserShowing = listOf("53", "206", "224", "225", "252", "99", "101",
            "1006", "1012", "1013", "1014", "1015", "1030", "1033", "1034", "1035", "1036", "1037", "1038",
            "1039", "1040", "1041", "1042", "1043", "1051", "1054", "1057", "1065", "1082", "1089", "1091", "1096")
```
или
```
val errorCodesFallback = listOf("9999", "231", "3", "3001")
```

Для примера тестовая карта 5000 0000 0000 0009 с недостатком средств

1. В приложении отображается экран ошибки от SDK с сообщением, но на сервер (callback URL) нам прилетает REJECT
2. На экране ошибки в SDK можно попробовать повторить оплату с другой карты, но из за первого шага у нас заказ уже аннулирован на сервере

Можно ли добавить флаг поведения интерфейса, чтобы можно было отключить экран ошибок на стороне SDK и во всех случаях выкидывать TinkoffAcquiring.RESULT_ERROR

По умолчанию оставить поведение как сейчас, но с возможностью переопределения

Вот часть когда где идет определение поведения выкидывания результат в onActivityResult или же вывода своего (SDK) экрана с ошибкой

```
fun handleException(throwable: Throwable) {
        loadState.value = LoadedState
        when (throwable) {
            is NetworkException -> changeScreenState(ErrorScreenState(AsdkLocalization.resources.payDialogErrorNetwork!!))
            is AcquiringApiException -> {
                val errorCode = throwable.response?.errorCode
                if (errorCode != null && (AcquiringApi.errorCodesFallback.contains(errorCode) ||
                        AcquiringApi.errorCodesForUserShowing.contains(errorCode))) {
                    changeScreenState(ErrorScreenState(resolveErrorMessage(throwable)))
                } else changeScreenState(FinishWithErrorScreenState(throwable))
            }
            else -> changeScreenState(FinishWithErrorScreenState(throwable))
        }
    }
```

В прошлых версиях насколько я помню ошибки всегда выкидывались наружу

**Comment by MaryAPc** [comment]
Здравствуйте! Добавлю такую опцию в следующей версии

**Comment by memphisprog** [comment]
Добрый день!

А когда планируется следующая версия?

**Comment by MaryAPc** [comment]
Здравствуйте! На в начале следующей недели

**Comment by MaryAPc** [comment]
Добавлено в версии 2.2.1
