### ISSUE TITLE
Отсутствует возможность тестирования рекурентых платежей

### ISSUE THREAD

**Issue by kimrgrey** [TinkoffCreditSystems/AcquiringSdkAndroid#23]
Мобильные приложения, в большинстве своем, предполагают, что пользователь добавляет карту через списание 1 рубля, а потом проходит через процедуру повторного списания, когда делает реальный заказ. И в API, и в SDK такая возможность вроде как есть. Проблема состоит в том, что ее нельзя никак проверить, потому что нет такого понятия как "тестовый магазин" или "тестовая карта". В личном кабинете есть тестовый терминал, но он предоставляет только возможность проходить те сценарии, которые предусмотрены там же. Нельзя добавить несколько карт, а потом погонять автоматические платежи.

**Comment by MaryAPc** [comment]
В данном репозитории есть модуль sample, который является тестовым магазином. Вы можете запустить его на устройстве, а также посмотреть реализацию в коде. К нему привязан тестовый CustomerKey. В тестовом магазине вы можете привязать тестовые карты, а затем протестировать рекуррентные платежи с этих карт. Тестовые карты могу прислать.
С помощью вашего тестового терминала вы сможете проверить привязку и платежи уже в своем приложении, передав в SDK данные тестового терминала.
Все тестовые терминалы могут работать только на тестовом окружении `AcquiringSdk.isDeveloperMode = true`
Деньги при этом списываться не будут.
Если есть пожелания к улучшению приложения тестового магазина, можете их написать здесь, либо могу подробнее рассказать как можно протестировать привязку и рекуррентные платежи в вашем приложении

**Comment by kimrgrey** [comment]
Немного не понял принцип работы тестового терминала. Правильно ли я понимаю, что для проведения тестовых платежей мне нужно переключить SDK в `isDeveloperMode = true` и я смогу выполнить любую оперцию, передав при этом данные тестового терминала? Какие карты я могу при этом использовать? Если мне нужно, чтобы, скажем, операция не прошла за недостактом средств или чтобы карта расценивалась как Visa или Master Card, какие номера и CVV я могу использовать?

**Comment by kimrgrey** [comment]
Может быть где-то есть документация, вроде этой: https://stripe.com/docs/testing, - или этой: https://yookassa.ru/developers/using-api/testing, - или этой: https://developers.cloudpayments.ru/#testirovanie?

**Comment by MaryAPc** [comment]
> Правильно ли я понимаю, что для проведения тестовых платежей мне нужно переключить SDK в `isDeveloperMode = true` и я смогу выполнить любую оперцию, передав при этом данные тестового терминала?

Да, верно.


> Какие карты я могу при этом использовать? Если мне нужно, чтобы, скажем, операция не прошла за недостактом средств или чтобы карта расценивалась как Visa или Master Card, какие номера и CVV я могу использовать?

Карты для тестирования успешного платежа:
5321300000000005
5321300000000013
5321300000000021
5321300000000039
5321300000000047
5321300000000054
Срок действия: 11/22
CVV: 123

Для карт ниже expdate и cvv любой.
5000000000000074 -- Pay при сумме > 1000 возвращает 51 (Not sufficient funds)
5000000000000777 -- Всегда успешный платеж, подтверждения и отмены
5000000000000009 -- Всегда не успешный платеж код 51 - не хватает средств
5000000000000017 -- В ответ на PAY всегда отдаем успех, на CONFIRM всегда ошибку 05, на CANCEL всегда успех.
5000000000000025 -- Успех на Pay и Confirm, на Cancel ошибка 76
5000000000000033 -- На запрос Pay таймаут на 1 минуту, потом отдаем код 05
5000000000000066 -- На Pay ошибка 54
5000000000000058 -- На Pay ошибка 41
5000000000000041 -- На Pay ошибка N7

Еще можно на прод окружении `isDeveloperMode = false` использовать тестовый терминал, тестовые карты для него есть в личном кабинете в разделе "тестирование". Но на тестовом терминале лучше не проводить интеграционные тесты, он больше подходит для разовых платежей, например для прохождения тест-кейсов в личном кабинете

Кроме того, возможно вводить данные реальных карт при тестировании, для тестирования 3DS проверок напрмер, опять же при `isDeveloperMode = true` деньги списываться не будут 


> Может быть где-то есть документация, вроде этой: https://stripe.com/docs/testing, - или этой: https://yookassa.ru/developers/using-api/testing, - или этой: https://developers.cloudpayments.ru/#testirovanie?

Сейчас у нас есть кейсы для тестирвоания в личном кабинете, я подняла вопрос о возможном внесении в документацию или станице на сайте расширенной информации по тестированию и картам

**Comment by MaryAPc** [comment]
Информация о тестировании будет внесена в документацию в начале следующего года. Также будет проведена работа по вашему фидбеку к статье на Хабре
