### ISSUE TITLE
Требуется возможность оплатить только системой быстрых платежей

### ISSUE THREAD

**Issue by lifeyonet** [TinkoffCreditSystems/AcquiringSdkAndroid#24]
Нельзя ли добавить что-то вроде:

FeaturesOptions.kt 
....
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /*
    Запрет оплатой карты при оплате Системой быстрых платежей
    */
    var cardPayNoFps: Boolean = false;
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
....

PaymentFragment.kt 
.....
        if (paymentOptions.features.fpsEnabled) {
            setupFpsButton()
            payButton.text = localization.payPayViaButton
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            if(paymentOptions.features.cardPayNoFps) {
                payButton.visibility = View.GONE
                orTextView.visibility = View.GONE
            }
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        } else {
            orTextView.visibility = View.GONE
            payButton.text = localization.payPayButton
        }
.....
тем самым при оплате быстрыми платежами можно будет убрать с экрана кнопку оплатить картой и слово или.
Нам требуется жесткое разделение по типу оплаты картой или СБП но, не на уровне "пользователь так решил",
 а явно при выборе типа платежа.

Спасибо.

**Comment by MaryAPc** [comment]
Здравствуйте! Если скрывать остальные элементы на экране оплаты, то в нем в принципе не будет смысла. Подойдет ли вам такая доработка: в SDK будет отдельный метод для запуска оплаты через СБП, а вы в своей разметке можете сделать например кнопку и по клику на нее вызывать этот метод? При вызове метода будет происходить то же самое, что и при клике на кнопку "Оплатить через СБП" на экране оплаты SDK + результат операции по СБП вернется в приложение

**Comment by lifeyonet** [comment]
Да, это был бы идеальный вариант.

**Comment by MaryAPc** [comment]
Передала коллегам на уточнение, в среду дадут ответ

**Comment by MaryAPc** [comment]
Задача поставлена в разработку, по срокам смогу сориентировать несколько позже

**Comment by MaryAPc** [comment]
Здравствуйте! Доработка в релизе в версии 2.3.0.  В классе TinkoffAcquiring добавлен метод payWithSbp, который вы можете вызвать по клику на кнопку в вашем приложении для запуска оплаты через СБП. 
В модуле sample добавлен пример вызова и обработка платежа, примеры верстки и стиля кнопок. В документацию добавлены дополнительные примеры стиля и рекомендации по использованию бренда СБП, ознакомьтесь с ними пожалуйста (стр 24)
https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/master/Android%20SDK.pdf
