### ISSUE TITLE
Проблема с возвратом статуса платежа через СБП

### ISSUE THREAD

**Issue by movdanil26** [TinkoffCreditSystems/AcquiringSdkAndroid#252]
Прикрепил видео, смотрите.
Если оплачиваю через любой банк по СБП, пока оплата не прошла, убираю своё приложение из таск менеджера, оплачиваю, возвращаюсь в программу, сообщения внутри моей программы об успешной оплате нет, а всё потому что по вашей документации результат должен вернуться в `onActivityResult` активности с тарифами (см. видео).

[video_2023-04-29_17-49-51.zip](https://github.com/tinkoff-mobile-tech/AcquiringSdkAndroid/files/11359435/video_2023-04-29_17-49-51.zip) 

Ок, а что, если пользователь не вернётся в активность? Из-за этой проблемы мне пришлось в прошлом году импортировать модуль ui, чтобы в функции `createPaymentListener()` в файле `ru.tinkoff.acquiring.sdk.viewmodel.PaymentViewModel.kt` (196-я строчка) добавить свой код в `onUiNeeded()` - сохранять у себя paymentId, 

![Снимок экрана 2023-04-29 174238](https://user-images.githubusercontent.com/66782790/235308716-4f058441-55ad-4794-a14f-efe4e197a64d.png)

чтобы затем в других активностях своего приложения на основе paymentId узнавать статус платежа

![Снимок экрана 2023-04-29 174534](https://user-images.githubusercontent.com/66782790/235308805-00d1d628-009c-45d6-ab81-687e69670353.png)

Помогите, пожалуйста, в активности для оплаты тарифа я использую лишь одну строчку
`tinkoffAcquiring.openPaymentScreen(this, mPaymentOptions, 100)`

Как мне, кроме `onActivityResult`, получить paymentId, чтобы я в других местах в приложении мог узнавать статус платежа?

Например, мне бы зарегистрировать тот же слушатель `PaymentListenerAdapter`, чтобы в `onUiNeeded `я мог получить paymentId. Но мне однозначно надо проверять в других местах статус платежа. А как это сделать без paymentId? Его неоткуда взять.

**Comment by danmov26** [comment]
Добрый день, здесь есть кому ответить?

**Comment by harcoPro** [comment]
Добрый день.
В версии 2.13.3 нет такой функциональности, что вы задумали.
В версии [3.0.0](https://github.com/tinkoff-mobile-tech/AcquiringSdkAndroid/blob/v3.0.0/ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/SbpPaymentProcess.kt) у вас будет возможность получать инстанс процесса и отслеживать его состояние (запускать процесс в сервисе или work manager-e, где хотите)

Обратите внимание, что в возможностях сдк не указанео хранение истории операций, поэтому апи в этих местах ограничено, по задумке, историю операций должен собирать ваш бек

**Comment by movdanil26** [comment]
Добрый день. А когда вы выпустите версию 3.0.0?
