### ISSUE TITLE
Поведение формы оплаты

### ISSUE THREAD

**Issue by memphisprog** [TinkoffCreditSystems/AcquiringSdkAndroid#26]
Если открывать форму оплаты не во весь экран, то во время процесса оплаты есть возможность кликнуть вне формы (по прозрачной части) и форма закроется выкинув во внешний мир событие отмены.

Но оплата по факту пройдет.

Может быть есть смысл блокировать события вне формы, а так же кнопки назад во время проведения операции?

**Comment by MaryAPc** [comment]
Здравствуйте! Сделаем доработку в следующей версии

**Comment by memphisprog** [comment]
Отлично

Я думаю это так же можно дополнительным параметром сделать

А когда планируется новая версия?

**Comment by MaryAPc** [comment]
Считаю что лучше сделать это как поведение по-умолчанию, потому что при закрытии экрана мы не отменяем платеж в любом случае. 
По сроку новой версии пока сложно сказать, еще определяемся с другой большой задачей. Но если эта доработка срочно нужна, то я могу сделать ее релиз приоритетнее

**Comment by memphisprog** [comment]
Буду очень благодарен, если она побыстрее будет реализована

**Comment by MaryAPc** [comment]
В конце этой недели будет релиз

**Comment by memphisprog** [comment]
Хорошо, ждем.
Спасибо

**Comment by MaryAPc** [comment]
@memphisprog по техническим причинам релиз переносится на понедельник

**Comment by MaryAPc** [comment]
Реализовано в версии 2.2.2
