### ISSUE TITLE
"lateinit property terminalKey has not been initialized" при попытке получить список карт

### ISSUE THREAD

**Issue by MonsWriter** [TinkoffCreditSystems/AcquiringSdkAndroid#27]
Здравствуйте! 

Нам нужно получить `rebill_id` для привязанной карты. При успешной привязке новой карты с помощью метода `openAttachCardScreen` SDK в результате возвращается только `EXTRA_CARD_ID`. `Rebill_id` мы здесь получить не можем. В этом случае я пытаюсь получить список карт с помощью `AcquiringSdk` и метода `getCardList`.

В результате отправки запроса getCardList приложение падает с ошибкой:
`kotlin.UninitializedPropertyAccessException: lateinit property terminalKey has not been initialized`

Не понимаю, почему так происходит, `terminalKey` я указываю при инициализации `AcquiringSdk`.
Может быть неправильно использую запрос? В документации нет примеров использования , в репозитории тоже не нашёл.

![photo_2020-12-08 21 37 51](https://user-images.githubusercontent.com/1092229/101505206-4d558b80-399e-11eb-96ae-8ebbb9926f0b.jpeg)

![photo_2020-12-08 21 37 55](https://user-images.githubusercontent.com/1092229/101505228-534b6c80-399e-11eb-8a93-23c712d221fa.jpeg)

**Comment by MaryAPc** [comment]
Здравствуйте! Немного неверный вызов метода, вы можете посмотреть пример вызова в тестах здесь https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/master/core/src/test/java/ApiSdkUnitTest.kt

Если коротко, можно использовать так:
```
sdk.getCardList { customerKey = "user-key" }
                    .execute(
                            onSuccess = { getCardListResponse -> }, 
                            onFailure = { exception -> }
                    )
```
Еще хочу обратить внимание на то, что методы в AcquiringSdk классе синхронные, то есть их вызов должен быть сделан на другом потоке, не на main, иначе будет ошибка

**Comment by MonsWriter** [comment]
Большое спасибо за быстрый ответ!
Теперь всё работает.

Уточнение, что вызов должен быть не на main, оказался для меня очень полезным. 👍

**Comment by MaryAPc** [comment]
Добавлю в документации в коде это уточнение 👍
