### ISSUE TITLE
Выбор предпочитаемой карты для оплаты

### ISSUE THREAD

**Issue by MonsWriter** [TinkoffCreditSystems/AcquiringSdkAndroid#28]
Здравствуйте! 

Мы используем Tinkoff Acquiring SDK в мобильном приложении для привязки банковских карт и для управления банковскими картами. Чтобы не создавать с нуля интерфейсы для работы с банковскими картами, мы используем реализованные в SDK интерфейсы, а именно методы `openAttachCardScreen` и `openSavedCardsScreen`.

Но при этом саму оплату мы хотим инициализировать с бэкенда, используя API Тинькофф Оплата. 

Как мы можем для этого определить, какая из привязанных карт является предпочитаемой для оплаты? В ответе на запрос на получение списка привязанных карт у каждой карты есть статус: активная, неактивная и удалённая. Активная - это и есть предпочитаемая? Если да, то каким образом мы можем изменить предпочитаемую карту в интерфейсе, предоставляемом SDK? В интерфейсе, который даёт метод `openSavedCardsScreen`, можно только удалить карту или привязать новую.

**Comment by MaryAPc** [comment]
Список карт, реализуемый методом openSavedCardsScreen действительно служит для того, чтобы покупатель мог привязывать и удалять свои карты. Активаня карта - это статус всех действующих привязанных карт, не предпочитаемая. 
Выбор карты как предпочитаемой, я так понимаю вам нужно для совершения дальнейших платежей, без предварительного выбора карты?

**Comment by MonsWriter** [comment]
> Выбор карты как предпочитаемой, я так понимаю вам нужно для совершения дальнейших платежей, без предварительного выбора карты?

Да, всё верно. Привязывать карту мы хотим через приложение, а инициализировать платёж с бэкенда, когда пользователь воспользовался нашей услугой.

**Comment by MaryAPc** [comment]
Доработка принята, постараюсь сделать в следующем релизе, к пятнице

**Comment by MonsWriter** [comment]
> Доработка принята, постараюсь сделать в следующем релизе, к пятнице
Отлично 👍 
Будем очень благодарны.

**Comment by MaryAPc** [comment]
@MonsWriter по техническим причинам релиз переносится на понедельник

**Comment by MaryAPc** [comment]
Добавлено в версии 2.2.2.
Теперь вы можете указать в опциях экрана списка карт возможность выбора пользователем карты, передав в FeatureOptions параметр userCanSelectCard = true.
Псле того, как пользователь выберет карту и закроет экран списка карт, в ваш код в onActivityResult вернется результат intent из которого вы можете получить cardId выбранной карты по ключу TinkoffAcquiring.EXTRA_CARD_ID.
Далее при следующем открытии экрана списка карт вы просто передаете этот cardId в FeatureOptions в параметр selectedCardId.
Если пользователь не выбрал карту, или удалил выбранную, то по ключу TinkoffAcquiring.EXTRA_CARD_ID вернется null.
Реализацию хранения cardId выбираете отвечающую вашим требованиям, рекомендую соблюдать методы безопасного хранения таких данных.

Также вы можете настроить отображение заголовка на экране списка карт и поменять его языковую локализацию

**Comment by MonsWriter** [comment]
Подскажите, пожалуйста, стоит ли ждать чего-то подобного в iOS версии? Я создал там Issue, но пока никто не отвечает: 

https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/issues/28

**Comment by MaryAPc** [comment]
Здравствуйте, да, такая возможность появится и в ios версии, но скорее всего в январе
