### ISSUE TITLE
Не могу найти метод получения информации об оплате после её проведения через карты

### ISSUE THREAD

**Issue by Abror96** [TinkoffCreditSystems/AcquiringSdkAndroid#3]

**Comment by MaryAPc** [comment]
Если вы вызываете экран оплаты через openPaymentScreen, то в метод передается третий параметр requestCode, соответственно результат оплаты вернется в вашу активити в метод onActivityResult. Далее, если resultCode = RESULT_OK, то из intent вы можете получить EXTRA_PAYMENT_ID - id операции (тип Long), и опционально может вернуться EXTRA_CARD_ID - id карты (тип String) с которой была произведена оплата.
