### ISSUE TITLE
Разъяснения по работе MainFormLauncher

### ISSUE THREAD

**Issue by fonrit** [TinkoffCreditSystems/AcquiringSdkAndroid#302]
Добрый день!
Разъясните пожалуйста работу MainFormLauncher, я так понимаю через MainFormLauncher можно открыть одну форму с оплатой различными способами (По карте, сбп, mirPay, TinkoffPat)

Так же можно открыть конкретные формы (По карте, сбп, mirPay, TinkoffPat) с помощью персональных лаучеров SbpPayLauncher, MirPayLauncher и т.д.

В моем случае я использую MainFormLauncher с флагом (fpsEnabled = false) но в форме отображается оплата через сбп, я так понимаю это происходит так как флаг fpsEnabled = true берется из личного кабинета ?

**Comment by harcoPro** [comment]
Добрый день.
Да, управление списком способов оплаты происходит в личном кабинете. 
Флаг `fpsEnabled` забыли удалить. Исправим в след. релизе.
Спасибо.
