### ISSUE TITLE
Шторка со статусом после совершения транзакции

### ISSUE THREAD

**Issue by fonrit** [TinkoffCreditSystems/AcquiringSdkAndroid#303]
Приветствую!
Заметил нововведение в v 3.0.0, после завершения транзакции со статусом Success/Failure теперь всегда отображается шторка со статусом Оплачено/Ошибка.
Могу согласиться что есть клиенты которым это нужно. Но можете пожалуйста добавить флаг по которому эти шторки можно будет отключить. Раньше их не было, пользователь шел в наш финальный экран и теперь появился доп. шаг (Который вообще не нужен)

**Comment by harcoPro** [comment]
Добрый день.
С данным предложением вы можете обратиться в службу поддержи.
Возможно, в одну из следующих версий он будет реализован.
