### ISSUE TITLE
Черный background в версии 2.2.2

### ISSUE THREAD

**Issue by piritus** [TinkoffCreditSystems/AcquiringSdkAndroid#31]
Здравствуйте. 
В версии 2.2.1 всё корректно
![20201219_162734](https://user-images.githubusercontent.com/8979384/102686063-a7184a00-4217-11eb-8686-b2841f38e994.jpg)

,а в 2.2.2 так...
![20201219_161835](https://user-images.githubusercontent.com/8979384/102686066-b13a4880-4217-11eb-8130-053b2e76265c.jpg)

**Comment by MaryAPc** [comment]
Здравствуйте! На какой версии android и на каком устройстве это происходит? Появляется сразу при открытии экрана или через какое то время?

**Comment by piritus** [comment]
Сразу. На эмуляторе 10 андроид. Завтра проверю на реальном

**Comment by MaryAPc** [comment]
Проверьте пожалуйста, на эмуляторах такое бывает

**Comment by piritus** [comment]
Да, на реальном устройстве всё корректно, спасибо

**Comment by Mozyra** [comment]
Такая же проблема с черным экраном на реальном устройстве, но я использую во Flutter через плагин. Воспроизводится при сворачивании и разворачивании приложения.
Версия 2.3.0
https://github.com/nk2IsHere/tinkoff_acquiring_sdk_flutter

**Comment by MaryAPc** [comment]
@Mozyra насколько я знаю, это особенность отрисовки приложений на flutter,  там несколько подругому это происходит, нежели чем у нативных приложений. К сожалению с этой проблемой помочь не смогу, с flutter знакома поверхностно
