### ISSUE TITLE
Ошибка шифрования карточных данных

### ISSUE THREAD

**Issue by MarkD1916** [TinkoffCreditSystems/AcquiringSdkAndroid#39]
Здравствуйте, не нашел в документации с чем связана ошибка. Пытаюсь сделать тестовый платеж картой тинькофф

**Comment by MaryAPc** [comment]
Здравствуйте! Обычно такая ошибка возникает, если есть ошибка в publicKey или других данных терминала. Следует вначале проверить их. 
Вы пытаетесь выполнить платеж на тестовом контуре с тестовым терминалом или прод контур и прод терминал? Платеж через экран оплаты, Google Pay или другой способ?

**Comment by MarkD1916** [comment]
Тестовый контур и тестовый терминал через экран оплаты. Проблема действительно оказалась в данных терминала, но теперь возникает ошибка "Что-то пошло не так" 
RequestCode как-то может на это повлиять?

**Comment by MarkD1916** [comment]
Такс - все порешал, спасибо, что ответили)

**Comment by Kosshitikhin** [comment]
@MarkD1916  а как порешали? у меня сейчас такая же поблема. для шифрования данных карт нужен publicKey?

**Comment by MarkD1916** [comment]
Если я правильно помню в данном кейсе мне просто предоставили не тот publicKey. Так что да, просто перепроверил данные.
А так да - он используется для шифрования данных, в доке так и написано. 
![изображение](https://user-images.githubusercontent.com/64790102/132254699-46185c23-e462-483c-8e5f-7d5036ab7af1.png)

**Comment by Kosshitikhin** [comment]
@MarkD1916 нашел публичный ключ, но шифрование. Так же происходить с ошибкой, так и не могу понять в чем дело

**Comment by MarkD1916** [comment]
Куска кода точно нет, но вообще у Тинькофф же есть отличное тестовое [приложение](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/tree/master/sample) для sdk - стяните его посмотрите как там все устроено, так же посмотрите приходят ли логи в консоли, что в них пишут
`AcquiringSdk.isDebug = true         // включение логирования запросов` 
Пройдитесь дебагером до вашего onActivityResult - посмотрите, какая ошибка возвращается там (иногда они отличаются от того что выдает вьюха), а ну и проверьте ваш TERMINAL_KEY. 
Пожалуй это все, что я мог бы посоветовать.
