### ISSUE TITLE
Недостаточно информативное сообщение об ошибке

### ISSUE THREAD

**Issue by aartikov** [TinkoffCreditSystems/AcquiringSdkAndroid#4]
Здравствуйте. При совершении платежа через экран оплаты отобразилась ошибка "Что-то пошло не так".
В логах вижу ответ от сервера:
```
{"Success":false,"ErrorCode":"1051","Message":"Недостаточно средств на карте.",
"TerminalKey":"xxx","Status":"REJECTED","PaymentId":"xxx","OrderId":"xxx","Amount":100000}
```

Ожидаемое поведение: более информативное сообщение об ошибке, например, "Недостаточно средств на карте."

**Comment by MaryAPc** [comment]
Будет исправлено в следующей версии. Сообщения будут информативные
