### ISSUE TITLE
Экран привязки карт

### ISSUE THREAD

**Issue by MarkD1916** [TinkoffCreditSystems/AcquiringSdkAndroid#40]
Здравствуйте! Еще такой вопрос - предусмотрена ли возможность перейти на экран привязки карт из экрана оплаты с помощью featuresOptions?

**Comment by MaryAPc** [comment]
Здравствуйте! Нет, такой возможности нет. На экране оплаты есть возможность перейти в список карт (если есть хотя бы 1 привязанная карта) и на экране списка карт уже есть возможность открыть экран привязки

**Comment by MarkD1916** [comment]
Благодарю!
