### ISSUE TITLE
Payment ID в GooglePay

### ISSUE THREAD

**Issue by MarkD1916** [TinkoffCreditSystems/AcquiringSdkAndroid#41]
Здравствуйте! Такой вопрос, в вьюхе оплаты через Tinkoff, `state = SelectCardAndPayState(paymentId = ownPaymentId)` есть ли возможность каким-то образом указать paymentid при оплате через GooglePay. И еще вопрос - из-за чего может происходить исключение "Этот продавец не зарегестрирован в сервисе Google Pay".
Заранее благодарю за ответ!

**Comment by MaryAPc** [comment]
Здравствуйте!
1) я правильно поняла, что вы хотите сначала вызвать Init, затем Google Pay и после этого подтвердить платеж, вызвав FinishAuthorize и передать в него ваш paymentId?
2) в Google Pay нужно зарегистрироваться, инструкция как это сделать в [документации](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/master/Android%20SDK.pdf), раздел Подключение Google Pay. Вы выполняли шаги, описанные там?

**Comment by MarkD1916** [comment]
Добрый день, спасибо за ответ)
Ну да, вопрос состоит в том где при оплате через GooglePay можно указать PaymentID для подтверждения платежа. 
Если платить не через GooglePay,  а через карту, то все paymentId можно отследить в  onResultActivity 

```
tinkoffAcquiring.openPaymentScreen(
            *контекст*,
            *опции платежа*,
            *requestCode*,
            state = SelectCardAndPayState(**paymentId = ownPaymentId**)
        )
```
|
|
|
|
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?){
  *проверили нет ли ошибок и все такое*
  data.getSerializableExtra(TinkoffAcquiring.EXTRA_PAYMENT_ID) == **paymentId** -> все ок делай платеж
}
```
По сути вы вроде как ответили на мой вопрос - наверное paymentID можно при оплате с GooglePay отследить следующий образом в PaymentListener

```
fun createPaymentListener(): PaymentListener{
        return object: PaymentListenerAdapter(){
            override fun onStatusChanged(state: PaymentState?) {
                if (state == PaymentState.STARTED) {
                    println("STARTED")
                }
                if (state == PaymentState.SUCCESS){
                    println("SUCCESS")
                    TinkoffSettings.tinkoffAcquiring.finishPayment(paymentID, token)
                    *продолжаем успешную работу*
                }

                if (state == PaymentState.STOPPED){
                    println("STOPPED")
                }
            }
```
Надеюсь оно так сработает

**Comment by MaryAPc** [comment]
Почти верно, в PaymentListener придет payment Id, но в метод onSuccess:
```
private fun createPaymentListener(): PaymentListener {
        return object : PaymentListenerAdapter() {

            override fun onSuccess(paymentId: Long, cardId: String?, rebillId: String?) {
                *получаем paymentId*
            }
            
            /////
        }
    }
```

а в onStatusChanged приходит просто статус, без доп объектов
