### ISSUE TITLE
Проблема в Release версии

### ISSUE THREAD

**Issue by ilia1103** [TinkoffCreditSystems/AcquiringSdkAndroid#44]
Добрый день, прошу вашей помощи,чтобы разобраться в этом вопросе. При сборке Debug все работает хорошо, оплата и чеки проходят. При сборке Release теряются строки в activity и не работает оплата. Поле items в коде точно должно заполняться(в debug точно заполняется)
Логи при нажатии на кнопку оплатить:
I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/Init
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Поле Items не должно быть пустым."}
I/System.out: Tinkoff Acquiring SDK: === Request done with fail

Ниже логи при запуске sdk:
I/System.out: Tinkoff Acquiring SDK: === Parameters: {"CustomerKey":"changed","TerminalKey":"changed","Token":"changed"}
W/View: requestLayout() improperly called by android.widget.FrameLayout{486f2da VFE...C.. ......I. 0,0-0,0 #7f09003b app:id/acq_activity_background_layout} during layout: running second layout pass
I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/GetCardList
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"7","Message":"Неверный статус покупателя.","Details":"Покупатель не найден.","CustomerKey":"changed"}
I/System.out: Tinkoff Acquiring SDK: === Request done with fail
Скриншот: Слева - debug версия, Справа - Release
![image](https://user-images.githubusercontent.com/80444674/113976560-f9728a80-9849-11eb-8cd9-fbd884daff37.png)

**Comment by MaryAPc** [comment]
Здравствуйте! Похоже что проблема с настройками proguard в релиз версии, добавте в файл proguard rules следующие строки:
```
-keep class ru.tinkoff.acquiring.sdk.localization.** { *; }
-keep class ru.tinkoff.acquiring.sdk.requests.** { *; }
-keep class ru.tinkoff.acquiring.sdk.models.** { *; }
```

**Comment by ilia1103** [comment]
Спасибо, очень оперативно решили проблему!))
