### ISSUE TITLE
Поддерживает ли View оплаты Тинькофф Autofill framework

### ISSUE THREAD

**Issue by MarkD1916** [TinkoffCreditSystems/AcquiringSdkAndroid#45]
Здравствуйте! Такой вопрос - предусмотрена ли возможность использовать Autofill framework для автоматического заполнения полей в View оплаты

**Comment by MaryAPc** [comment]
Здравствуйте! В данный момент нет, но мы уже рассматриваем такую возможность

**Comment by MarkD1916** [comment]
Спасибо за ответ! Тогда запоминать данные карты пользователя можно с помощью AttachCardScreen, но при попытке добавить карту происходит ошибка "Неверный статус карты", как интерпретировать данную ошибку?
![изображение](https://user-images.githubusercontent.com/64790102/114396163-e80ce380-9ba5-11eb-8055-61002e3e3ac5.png)

**Comment by MaryAPc** [comment]
Такая ошибка обычно выстречается, если карта уже была добавлена, вы можете это проверить? это можно сделать вызвав GetCardList или открыть экран оплаты openPaymentScreen, передав в параметры ваш CustomerKey

**Comment by MarkD1916** [comment]
Да я проверил через экран оплаты - по логам пишет, что покупателя нет, передаю точно один и тот же CustomerKey
![изображение](https://user-images.githubusercontent.com/64790102/114530268-74c1ab00-9c53-11eb-8a01-861b2ac3c6b7.png)

**Comment by MaryAPc** [comment]
Такой CustomerKey еще не зарегистрирован в системе, поэтому не добавляется карта. Подробнее отвечала здесь https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/issues/43#issuecomment-811949606 
Поэтому клиент либо сначала должен совершить первую покупку, либо вы должны добавить клиента на своем сервере (если у вас таковой имеется) методом AddCustomer. После любого из этих действий карты будут привязываться без ошибки

**Comment by MarkD1916** [comment]
Спасибо!
