### ISSUE TITLE
Терминал не найден

### ISSUE THREAD

**Issue by dvfxru** [TinkoffCreditSystems/AcquiringSdkAndroid#46]
Добрый день. При попытке оплаты через SDK получаю ошибку:
`{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Терминал не найден."}`
Используется тестовый терминал (*DEMO). AcquiringSdk.isDeveloperMode = true
Такая же ошибка в sample-приложении, если заменить данные терминала на свои

**Comment by MaryAPc** [comment]
Здравствуйте! Терминал не подключен к тестовому окружению, пришлите мне его полное название и я передам коллегам на подключение

**Comment by dvfxru** [comment]
Терминал 1618186907914DEMO
Это можно как-то самостоятельно сделать? Или куда обращаться в следующий раз? Не сюда же писать

**Comment by MaryAPc** [comment]
Самостоятельно нет, нужно обращаться в поддержку, лучше это сделать через личный кабинет

**Comment by MaryAPc** [comment]
Терминал добавили на тестовое окружение, можете проверить

**Comment by dvfxru** [comment]
Спасибо

**Comment by simhali** [comment]
Здравствуйте, у меня такая же проблема. Получаю вот такой ответ:
{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Терминал не найден."}
[Response] InitResponse(Success: false, Status: null, ErrorCode: 9999, Message: Неверные параметры., Details: Терминал не найден., TerminalKey: null, Amount: null, OrderId: null, PaymentId: null, PaymentURL: null)
