### ISSUE TITLE
Покупатель не найден, хотя оплата прошла успешно

### ISSUE THREAD

**Issue by MarkD1916** [TinkoffCreditSystems/AcquiringSdkAndroid#47]
Здравствуйте! 
Открываем форму оплаты - покупатель не найден, что нормально еще не было успешных платежей
![изображение](https://user-images.githubusercontent.com/64790102/114847790-c3537e80-9de6-11eb-9779-a65873250aba.png)
Затем происходит оплата - оплата проходит успешно, деньги списываются, далее привожу логи

Tinkoff Acquiring SDK: ===Parameters: {"PaymentId":"#####","TerminalKey":"######","Token":"######"}

Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/Check3dsVersion

Tinkoff Acquiring SDK: === Got server response: {"Success":true,"ErrorCode":"0","Message":"OK","Version":"1.0.0"}

Tinkoff Acquiring SDK: === Request done with success, sent for processing

Tinkoff Acquiring SDK: === Parameters: {"PaymentId":"######","TerminalKey":"######","Token":"######"}

Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/FinishAuthorize

Tinkoff Acquiring SDK: === Got server response: {"Success":true,"ErrorCode":"0","TerminalKey":"#####","Status":"3DS_CHECKING","PaymentId":"#####","OrderId":"####","Amount":100,"ACSUrl":"https://ds1.mirconnect.ru:443/vbv1/pareq", "MD":"ACQP-7843619956","PaReq":"#####"}

Tinkoff Acquiring SDK: === Request done with success, sent for processing

Tinkoff Acquiring SDK: === Parameters: {"PaymentId":"######", "TerminalKey":"######", "Token":"######"}

Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/GetState

Tinkoff Acquiring SDK: === Got server response: {"Success":true,"ErrorCode":"0","Message":"OK","TerminalKey":"####","Status":"CONFIRMED","PaymentId":"####","OrderId":"#####","Amount":100}

Tinkoff Acquiring SDK: === Request done with success, sent for processing

И вот я снова открываю экран оплаты

Tinkoff Acquiring SDK: === Parameters: {"CustomerKey":"#####","TerminalKey":"######","Token":"######"}

Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/GetCardList

Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"7","Message":"Неверный статус покупателя.","Details":"Покупатель не найден.","CustomerKey":"#####"}

Tinkoff Acquiring SDK: === Request done with fail

Для тестирования мы воссоздавали тестовую среду из вашего приложения-примера, в тестовой среде все работало. Можно ли предположить в чем проблема? Оплату я производил с карты сбербанка. Заранее благодарю за ответ!

**Comment by MarkD1916** [comment]
Вот еще скрин настроек
![изображение](https://user-images.githubusercontent.com/64790102/114852102-23e4ba80-9deb-11eb-9d6d-7aade8b5f61d.png)

**Comment by MaryAPc** [comment]
Здравствуйте! Проблема пока не очевидна, сперва нужно убедиться, что точно одинаковый customerKey передается, это можно проверить по параметрам в логах:
1 GetCardList
2 Init
3 GetCardList после покупки

Еще не вижу в ваших логах метода Init, первый вызывается Check3dsVersion (после GetCardList), вы вызываете метод openPaymentScreen для открытия экрана оплаты? с какими параметрами?

**Comment by MarkD1916** [comment]
Да, вот метод открытия экрана оплаты и параметры, которые туда передаются
![изображение](https://user-images.githubusercontent.com/64790102/114859636-b426fd80-9df3-11eb-9a6a-646d513a750e.png)
Метода Init действительно нет в логах.
К сожалению я не могу выложить в открытый доступ CustomerKey клиента, но он точно одинаковый в методах GetCardList до и после успешной покупки, как и в методе GetState, подкрепляю скрином, где в поиске консоли вбил CustomerKey
![изображение](https://user-images.githubusercontent.com/64790102/114862604-66ac8f80-9df7-11eb-9da3-5f3d7636cd47.png)

**Comment by MaryAPc** [comment]
У вас в параметрах метода openPaymentScreen  указан state = SelectCardAnpPayState, этот state используется, если вам нужно вызвать метод Init самостоятельно, где то до открытия экрана, вы это действительно делаете, или по каким то другим причинам указали такой state?

**Comment by MarkD1916** [comment]
Такой state был указан по причинам: https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/issues/11
У нас тоже проверка статуса происходит на стороне бэка, метод init до открытия экрана не вызывается.

**Comment by MaryAPc** [comment]
Поняла, у метода Init есть параметр customerKey, который как раз свяжет оплату с покупателем и его картой, скорее всего в том месте, где у вас вызывается Init, некорректно передается customerKey или не передается вовсе, проверьте пожалуйста

**Comment by MaryAPc** [comment]
customerKey, передаваемый в метод Init должен быть тот же самый, который используется в приложении для конкретного клиента

**Comment by MarkD1916** [comment]
Спасибо, получилось)
