### ISSUE TITLE
Возможность запустить экран оплаты с заранее выбранной картой

### ISSUE THREAD

**Issue by aartikov** [TinkoffCreditSystems/AcquiringSdkAndroid#5]
Здравствуйте. Есть ли возможность запустить экран оплаты, указав id привязанной карты?
В моем приложении выбор карты происходит на отдельном экране перед оплатой.
Мне нужно, чтоб на экране оплаты не было барабана выбора/добавления карт, а был только один элемент - указанная карта.

**Comment by MaryAPc** [comment]
Здравствуйте! Возможности открыть экран оплаты с выбранной картой нет, но есть другое решение для вашего случая. Так как у вас есть свой экран с выбором карты, то далее вы можете провести платеж с помощью вызова метода initPayment класса TinkoffAcquiring (например вызывать его по клику на вашу кнопку оплатить). Метод принимает параметры CardData (pan, date, cvc) и PaymentOptions и запускает полный процесс оплаты (асинхронно). В этом случае экран sdk потребуется только в случае если нужно будет пройти 3DS проверку. 

Чтобы отслеживать процесс и реагировать на события, нужно реализовать интерфейс PaymentListener и передать реализацию в метод subscribe.

Пример:
```
val tinkoffAcquiring = TinkoffAcquiring(terminalKey, password, publicKey)

payButton.setOnClickListener {
                showProgressDialog()
                tinkoffAcquiring.initPayment(CardData("0000000000000000", "11/22", "111"), createPaymentOptions())
                .subscribe(createPaymentListener())
                .start()
}

=======

private fun createPaymentListener(): PaymentListener {
        return object : PaymentListenerAdapter() {

            override fun onSuccess(paymentId: Long, cardId: String?) {
                hideProgressDialog()
                onSuccessPayment()
            }

            override fun onUiNeeded(state: AsdkState) {
                hideProgressDialog()
                tinkoffAcquiring.openPaymentScreen(
                        this@PayableActivity,
                        createPaymentOptions(),
                        PAYMENT_REQUEST_CODE,
                        state)
            }

            override fun onError(throwable: Throwable) {
                hideProgressDialog()
                showErrorDialog()
            }
        }
    }
```

Подробнее про процесс оплаты без открытия экрана можно посмотреть в [документации ](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/master/Android%20SDK.pdf) параграф "Проведение платежа без открытия экрана оплаты" стр 32.

**Comment by aartikov** [comment]
@MaryAPc Спасибо за ответ.
Метод `tinkoffAcquiring.initPayment` практически то что мне нужно. Но его первый параметр имеет тип `CardData`, а мне хотелось бы передать сохраненную карту - `AttachedCard`.

**Comment by MaryAPc** [comment]
Тогда можно поступить так:
Вместо метода initPayment вызывать метод finishPayment, который принимает paymentId и PaymentSource (AttachedCard является PaymentSource) далее схема та же с подпиской на события. А перед вызовом метода finishPayment вызвать инициацию платежа из модуля core. Этот вызов будет синхронный, нужно будет вызывать в другом потоке, а результат обработать на main:
```
val sdk = AcquiringSdk(terminalKey, password, publicKey)
sdk.init {
            //параметры как PaymentOptions 
            amount = 2000
            orderId = randomOrderId
            chargeFlag = isRecurrent
            customerKey = key
            recurrent = isRecurrent
            //.... и другие
        }.execute(
                onSuccess = {
                    //передать в main поток
                    tinkoffAcquiring.finishPaymen(it.paymentId, attachedCard)
                },
                onFailure = {
                    //передать в main поток
                    showErrorDialog()
                })
```

Мы рассмотрим возможность совершения платежа через initPayment с параметром AttachedCard и возможно добавим в следующей версии

**Comment by aartikov** [comment]
Спасибо

**Comment by MaryAPc** [comment]
В версии 2.0.2 добавлен метод initPayment с возможностью передать AttachedCard

**Comment by Tetraquark** [comment]
@MaryAPc 
Подскажите, пожалуйста, а реализация данной функциональности совсем не планируется?

> запустить экран оплаты, указав id привязанной карты

**Comment by MaryAPc** [comment]
@Tetraquark Сейчас задач на реальзацию такого функционала нет. Смысл экрана оплаты в том, чтобы пользователь мог на нем выбрать карту, ввести новую, посмотреть список карт (управлять им, если нужно) и оплатить заказ. Если у вас есть также, как и у автора вопроса, свой экран с выбором карты, то по сути надобность в экране sdk отпадает. Или у вас другой кейс?

**Comment by Tetraquark** [comment]
Кейс, как я понимаю, примерно такой же - список карт с функцией выбора карты для оплаты реализованы в самом приложении, а вот непосредственно для процесса оплаты хочется использовать готовый экран/диалог из sdk :)

**Comment by MaryAPc** [comment]
Давайте представим примерный флоу оплаты с точки зрения пользователя в этом случае: в корзине он нажимает кнопку оплатить -> выбрал карту -> нажимает оплатить -> появляется экран sdk с выбранной картой и снова нужно нажимать оплатить) 
последний шаг кажется излишним, ведь чем проще происходит оплата и меньше шагов, тем лучше для пользователя

**Comment by Tetraquark** [comment]
У разных приложений бывает разный ui/ux, поэтому в разных ситуациях могут быть разные подходы. В моем случае список подключенных банковских карт находится на отдельном экране условного профиля пользователя, в котором выполняется всё управление картами (добавление, удаление) с собственным ui. Процесс оплаты запускается на других экранах при покупке разных услуг и подписок, для которого используется готовый ui. Поэтому тут сценарий может быть такой: пользователь заранее может добавить карту на экране профиля и указать её как карту по-умолчанию для оплаты -> перейти в список продуктов -> нажать кнопку оплаты -> появляется диалог оплаты с уже готовой картой.

**Comment by MaryAPc** [comment]
Тогда здесь может случиться такой кейс - пользователю открылся экран с картой, но он вдруг понял, что ему нужно оплатить с другой карты. ему придется уходить с экрана оплаты в профиль, менять карту и возвращаться к оплате, что негативно с точки зрения ux

**Comment by MaryAPc** [comment]
Возможность будет добавлена в версии 2.1.2

**Comment by MaryAPc** [comment]
Добавлено в версии 2.2.0
