### ISSUE TITLE
При оплате через Google Pay ошибка "Параметр EncryptedPaymentData не сопоставлен"

### ISSUE THREAD

**Issue by Akorius** [TinkoffCreditSystems/AcquiringSdkAndroid#50]
Добрый день! 
При оплате получаю ошибку с кодом 259. 
Данная ошибка не описана в документации, подскажите, в чем может быть причина?
![111](https://user-images.githubusercontent.com/20949752/121003248-fe927e00-c795-11eb-97f9-c78f677f1c5f.png)

**Comment by MaryAPc** [comment]
Здравствуйте! Вижу что проверяете платеж в прод среде, а в тестовой среде https://rest-api-test.tcsbank.ru/rest платеж проходит?
И второй вопрос, были ли выполнены все шаги по подключению из документации? 
![image](https://user-images.githubusercontent.com/22216370/121009823-cfdccd80-c7be-11eb-8320-3c858e9a1207.png)

**Comment by Akorius** [comment]
Спасибо, действительно, была проблема с Google и их регистрацией приложения.
