### ISSUE TITLE
Отсутствует поле Token

### ISSUE THREAD

**Issue by vbeskrovnov** [TinkoffCreditSystems/AcquiringSdkAndroid#54]
Здравствуйте!
Подскажите, как выполнить запрос без поля token, которое было удалено в [коммите](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/commit/8bab7974205b7b0e3a0e3f461593ef0808df1fef)?

**Comment by MaryAPc** [comment]
Здравствуйте! Поле Token больше не требуется для запросов, можете вызывать запросы без передачи password и без токена

**Comment by mit-73** [comment]
Здравствуйте @MaryAPc, для запроса [Сancel](https://www.tinkoff.ru/kassa/develop/api/payments/cancel-request/) все также требует token:
`{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Поле Token не должно быть пустым."}`

Не могли бы Вы проверить это?

**Comment by MaryAPc** [comment]
Метод Cancel не поддерживается в SDK, предназначен для вызова с бекенда, для него токен всё еще нужен

**Comment by mit-73** [comment]
@MaryAPc тогда такой вопрос: будет ли Token поддерживаться для всех запросов как это было раньше? Или его уберут окончательно в будущих версиях?

**Comment by MaryAPc** [comment]
Вопрос касается только методов в SDK или для бэка тоже?

**Comment by mit-73** [comment]
Для бэка тоже

**Comment by MaryAPc** [comment]
сейчас убрали токен для методов SDK, для бэка пока не предполагаются подобные действия

**Comment by vbeskrovnov** [comment]
Спасибо!
