### ISSUE TITLE
Возможность запустить экран сохраненных карт

### ISSUE THREAD

**Issue by Akree** [TinkoffCreditSystems/AcquiringSdkAndroid#6]
Здраствуйте)
Хотелось бы иметь возможность запускать экран с сохраненными картами, чтобы иметь возможность редактировать список карт не привязываясь к каком-либо платежу.
Если такое планируется в будущем, то когда?)

**Comment by MaryAPc** [comment]
Здравствуйте! Такая возможность не планировалась. Поставили задачу на рассмотрение, но по сроку сказать не могу к сожалению
