### ISSUE TITLE
На экран оплаты нельзя передать заголовок длиннее 20 символов.

### ISSUE THREAD

**Issue by aartikov** [TinkoffCreditSystems/AcquiringSdkAndroid#9]
Здравствуйте.
Если передать на экран оплаты в orderOptions свойство title длинее 20 символов, то при оплате отображается ошибка "Что-то пошло не так".
Логи: `{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Размер поля PayForm должен быть от 1 до 20."}`

Пожалуйста, исправьте эту проблему. В моем приложении требуется отображать более длинные названия товаров.

**Comment by MaryAPc** [comment]
Здравствуйте! Я уточню у коллег с API, могут ли это исправить. Пока что могу предложить сократить название title, а полное название указывать параметре description, который вмещает 250 символов.

**Comment by MaryAPc** [comment]
Будет исправлено в версии 2.0.3. Сейчас можете передавать в title короткое название заказа, либо не передавать его вовсе, а в description описание заказа
